### ISSUE TITLE
Upgrade Aerosharp client to .net 6 and Aerospike 6.0.0

### ISSUE THREAD

**Issue by awesor** [wayfair-incubator/AeroSharp#162]
## Problem Statement
In order to stay up to date with the latest and greatest features made available by
@BrianNichols and team over at Aerospike, I&#39;d like to start a conversation about making a
**major version** upgrade to this client to upgrade to the Aerospike csharp package version
6.0.0.
## Proposed Solution
The only way that I see us being able to stay up to date with this and future versions of
Aerospike is to not only upgrade the NuGet package, but also to upgrade the overall AeroSharp
project to target .net core 6.0. This is definitely a major upgrade considering we&#39;re currently
running .net standard 2.1. From my research, there are a number of really interesting behind
the scenes benefits that we&#39;ll be able to take advantage of that are built into the new netcore
version (JIT, GC, etc.).
By making a major version upgrade, we&#39;re indicating that we are breaking projects if folks do
decide to install this latest version on their own projects. Microsoft has been very clear about
the future of C# and I think we should create a new version here to reflect this major update.
## Alternatives Considered
None really - there&#39;s not much we can do here since Aerospike has decided to remove support
in future versions for non-.netcore projects. I recognize however
## Additional Context
As mentioned in their pre-requisites for the client, this does seem to be the new path forward for
interacting with Aerospike, unless clients want to stay back in the 5.* versions:
https://github.com/aerospike/aerospike-client-csharp#aerospike-c-client-package.

**Comment by adenisov** [comment]
First I find this inevitable and as we're already talking here about up-versioning my couple cents will be to align Aerosharp versioning with Aerospike and .NET overall e.g. bump to `6.0.0` from `0.3.1`

**Comment by wbaldoumas** [comment]
Thanks for opening this up @awesor!

I agree that we should make this upgrade so that we can maintain parity with the Aerospike client versioning. Dropping support for .NET Standard is also something that seems inevitable to me.

@awesor if you'd like to snag implementing this, feel free to. If not, perhaps someone else in this issue thread would be interested. I unfortunately will be unavailable in April, so I personally wouldn't be able to work on this upgrade until May.
