### ISSUE TITLE
Default batch size for bulk reads is too high

### ISSUE THREAD

**Issue by awesor** [wayfair-incubator/AeroSharp#168]
## Description

Under investigation still, but we've noticed in production for our team's usage of this library that the batch size default of 5,000 is too large at scale.  Internally, we reduced to 4,500 and saw improvements in our latency and reduction in the amount of "Max Connections" produced per application.

For our use case, we had numerous requests to our API to fetch 10k - 50k keys at once, broken up into 5,000 batches.  As I understand it from @tfaulkes, Aerospike's internal batch processing system has a max of 5,000 - I don't know if it's safe for this library to default to that max, but as described above, we're seeing improvements with just a slight reduction.

The only "documentation" about this that I could find was listed [here](https://developer.aerospike.com/blog/batch-operations-in-aerospike#batch-size-limit).  I'm not sure what other users' server-side batch sizes are, but if the default is 5,000, perhaps it'd be better to lower this on the client end and send less keys per command.

## Expected Behaviour

I'd expect the library to perhaps default to 50% of the max batch size in Aerospike: 2,500.

This is a difficult thing to test locally I will say!

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/AeroSharp/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by farmerau** [comment]
What property are you suggesting we change? The abstracted `MaxConcurrentBatches` or some other property?

**Comment by wbaldoumas** [comment]
This is something I'd be open to, assuming we aren't artificially capping the max batch size for clients of this library to something lower than what the underlying Aerospike client supports. +1 to @farmerau's question above, though.

**Comment by farmerau** [comment]
To @wbaldoumas's point, I'd expect we'd:

- Consider this a breaking change
- Allow users to override the setting if they think they know better (if we already don't)
