### ISSUE TITLE
ReadModifyWritePolicy is retrying only on Aerospike Generation Error

### ISSUE THREAD

**Issue by dmardanov34** [wayfair-incubator/AeroSharp#172]
Hello! 

I was working on switching from Write to ReadModifyWrite and noticed something.

When ReadModifyWrite is executed, WritePolicy's [retries are set to 0](https://github.com/wayfair-incubator/AeroSharp/blob/main/src/AeroSharp/DataAccess/KeyValueAccess/KeyValueStore.cs#L160C35-L160C35).

To still support the retry capabilities, Polly's Retry Policy is introduced and ReadModifyWritePolicy is used to control max retries, wait times, etc. 

Said policy seems to [handle](https://github.com/wayfair-incubator/AeroSharp/blob/main/src/AeroSharp/Utilities/ReadModifyWritePolicyFactory.cs#L21) **ONLY** the generation conflict exception:
`_policyBuilder = Policy
               .Handle<OperationFailedException>(ex =>
                    ((AerospikeException)ex.InnerException).Result == ResultCode.GENERATION_ERROR);`
                    
I could not find a way to tune the exception handling from the client side, since PolicyBuilder is not exposed.

I think that when switching from the Write to ReadModifyWrite, we are losing the retry capabilities of the Write operation. I'd like to know if there was an intention behind this approach, or should ReadModifyWrite policy retry on any exception?

**Comment by farmerau** [comment]
Hi @dmardanov34, thanks for creating this issue.

As you've found in the code, the `WritePolicy`'s retries are set to 0 and it [is explained in the lines preceding it to avoid confusion](https://github.com/wayfair-incubator/AeroSharp/blob/main/src/AeroSharp/DataAccess/KeyValueAccess/KeyValueStore.cs#L156-L159).

Take a look at [Aerospike's tutorial around the Read-Modify-Write pattern](https://developer.aerospike.com/tutorials/python/transactions_rmw_pattern#using-generation-check) and see if this clears things up, at least in regard to the overriding of that setting.

At the time of writing, we elected to allow additional exceptions to flow to the user to be handled as they are in other parts of the library. We wouldn't want to expose Polly as a part of our contract to the user, but I can empathize with wanting the policy to retry the entire RMW operation on other exceptions (if you _really_ know what you're doing).

To do this, we'd want to modify the [ReadModifyWritePolicy](https://github.com/wayfair-incubator/AeroSharp/blob/ce2f061bcf643924f51d891fb60c6e9a75a11a6e/src/AeroSharp/Utilities/ReadModifyWritePolicy.cs) to include an _optional_ list of exceptions it should also handle and adjust the policy factory accordingly. In practice, this may further degrade performance and would need to be tested.

Curious to hear thoughts from @awesor and @wbaldoumas

**Comment by farmerau** [comment]
@wbaldoumas I like your suggested options for handling this, if we find a compelling need I think this is the way.

@dmardanov34 what are your thoughts here?

**Comment by dmardanov34** [comment]
Thanks for sharing your thoughts on this, @farmerau, @wbaldoumas!

I like the suggested extension for the KeyValueStore Builder, but if indeed, a strong need for customization will come, I do not see a problem with keeping things as-is. The only not I would like to make is that it could be useful to mention this shift in the retry behaviour when switching from write to read-modify-write in the documentation, so it would be more obvious to the user.

**Comment by wbaldoumas** [comment]
My preference here is updating the docs, similar to how you describe, and leave the existing behavior as is unless there is a strong need for retry customization, since what is currently in place aligns with the suggested implementation provided by Aerospike.
