### ISSUE TITLE
Address/Suppress Warnings and Treat Warnings as Errors

### ISSUE THREAD

**Issue by wbaldoumas** [wayfair-incubator/AeroSharp#174]
## Problem Statement

The project exhibits many compiler warnings when compiled, which are made obvious on open pull requests ([example](https://github.com/wayfair-incubator/AeroSharp/pull/173/files)). These cause unnecessary noise both within IDE and pull request settings. Warnings should also be addressed in and of their own right because they've been set as warnings for a reason.

## Proposed Solution

Work through the existing warnings and either suppress them (via `.editorconfig` changes) if it is reasonable to do so, or address them.

Once there are no warnings remaining, we should set `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` within the project files to make it impossible to introduce warnings again in the future.

Depending on the changes required, this may be a major version bump (if we need to remove deprecated methods, as an example).

**Comment by awesor** [comment]
+1 to this!  Definitely a good idea and something I'll make sure to tidy up on my PR.

**Comment by wbaldoumas** [comment]
Commenting to remove stale status. @brittany-alves has started work on this in https://github.com/wayfair-incubator/AeroSharp/pull/176.
