### ISSUE TITLE
Publish Library Documentation

### ISSUE THREAD

**Issue by jdhmtl** [wayfair-incubator/AeroSharp#2]
## Problem Statement

In order to make the most use of this library, users must be provided with documentation, both in the form of granular, API-level documentation, and manually written examples, tutorials, etc. This documentation should live alongside the code for offline reference, and be automatically published when new versions of the library are released.

## Proposed Solution

Leverage [DocFX](https://dotnet.github.io/docfx/) to build out a documentation site from both the C# code and a specified `docs` directory. Consider the [DocFX Action](https://github.com/marketplace/actions/docfx-action) to automatically build and publish the site to GitHub Pages.

## Alternatives Considered

[Read the Docs](https://readthedocs.org/) is another popular option. It supports versioned documentation, which DocFX currently does not, and offers GitHub integration for ease of publishing. Drawbacks include potentially tying the Read the Docs account to an individual, having yet another account to juggle, and a lack of tooling to parse C# code into something Read the Docs would recognize.

## Additional Context

[DocFX JSON configuration](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#3-docfxjson-format)
[DocFX plans to support versioned documentation](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md)

**Comment by wbaldoumas** [comment]
This is resolved. Docs are published on merge to `main` and available here: https://wayfair-incubator.github.io/AeroSharp/
