### ISSUE TITLE
Support Aerospike Maps

### ISSUE THREAD

**Issue by wbaldoumas** [wayfair-incubator/AeroSharp#9]
## Problem Statement

This library would benefit from having support for Aerospike maps. Records in Aerospike can store a map inside a bin. This allows for manipulation of key-value pairs directly on the Aerospike server.

## Proposed Solution

Initial draft of proposed solution: https://github.com/wayfair-incubator/AeroSharp/pull/170

## Additional Context

https://www.aerospike.com/docs/guide/cdt-map.html
https://www.aerospike.com/docs/guide/cdt-map-ops.html
https://www.aerospike.com/apidocs/csharp/Index.html

**Comment by awesor** [comment]
I'd actually like to reopen this issue as I think that utilizing Aerospike's data types might gain folks who use this library some great performance improvements by utilizing native data types.

**Comment by farmerau** [comment]
I don't think we have a way to bypass stale issues (other than by making activity). Do you have availability to work on this? :)

**Comment by wbaldoumas** [comment]
@awesor @farmerau I've picked this up to work on. 

The plan is to provide an API similar to what we've done for lists:

- [IList](https://github.com/wayfair-incubator/AeroSharp/blob/main/src/AeroSharp/DataAccess/ListAccess/IList.cs): Provides access to a single list stored remotely on Aerospike.
- [IListOperator](https://github.com/wayfair-incubator/AeroSharp/blob/main/src/AeroSharp/DataAccess/ListAccess/IListOperator.cs): Provides access to list operations for lists containing type <typeparamref name="T"/> stored remotely on Aerospike.

Let me know if you have any questions/suggestions. 👍🏻

**Comment by farmerau** [comment]
Hmm, I'm really regretting that we used the `IList` name, even though it's in a separate namespace. This will make some code look less than appealing.

Practically speaking, we'll need to qualify with `System.Collections.Generic or `AeroSharp.DataAccess.ListAccess` or alias it.

Would it be reasonable for us to create an alias interface and present that as the "first class"? Of course, we can keep the original interface for backwards compatibility but it would help us pay this down now.

**Comment by wbaldoumas** [comment]
That's true, but do you see the same naming issue with `IMap`? 

I only mentioned `IList` here in terms of the design following a similar API convention of providing access to a single map in Aerospike, and providing `IMapOperator` for operating against multiple maps.

I do agree with all of your points about the `IList` usage though - taking your naming suggestion here, would you suggest that I call this `IAsyncMap` rather than `IMap`, then?

**Comment by farmerau** [comment]
Just quick searches only show IMAP in the context of email. However, for consistency and discoverability, it might make sense to name it similarly.

Unless there’s something else in the BCL for imap that I didn’t find quickly.

**Comment by wbaldoumas** [comment]
>Just quick searches only show IMAP in the context of email. However, for consistency and discoverability, it might make sense to name it similarly.

Yeah, that's my thinking. I'm going to call these `IMap` and `IMapOperator` to match the list interface naming convention. I don't think there's nearly as much chance of a naming collision, like you said. 

I should have a draft PR for a very small subset of map operations tomorrow and will post here. Thanks for the feedback so far! 😄

**Comment by wbaldoumas** [comment]
@awesor @farmerau here's a first crack at this: https://github.com/wayfair-incubator/AeroSharp/pull/170

Feel free to take a look and add any question/comments/constructive criticism you might have. 😄

**Comment by wbaldoumas** [comment]
This auto-closed since my initial PR was merged. Re-opened since @awesor is going to be contributing some before we prepare a release.

**Comment by awesor** [comment]
Yep - working on https://github.com/wayfair-incubator/AeroSharp/pull/171. 

Curious for the group here as we're preventing release until we build up a set of methods for maps: what's our min set of methods?  

Are there any in particular that folks would expect to be supported from the release?

**Comment by wbaldoumas** [comment]
I think with the introduction of the `GetByRank` methods in your upcoming PR, we can do a small release with what we've got put together so far. If other methods are needed we can add them in a follow up release.

**Comment by awesor** [comment]
Awesome, I've been trying to get the GetByKeyList method as well that might enable folks to pull multiple elements from a map at once rather than multiple GetByKey commands.

However, definitely going to just try and get one thing up solid and then go from there if I have more time!  Exciting things with these maps and lists!
